# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
    - id: check-merge-conflict
    - id: check-yaml

- repo: https://github.com/kynan/nbstripout
  rev: master
  hooks:
    - id: nbstripout

- repo: https://github.com/asottile/pyupgrade
  rev: v2.7.2
  hooks:
    - id: pyupgrade
      args: [--py36-plus]

- repo: https://github.com/ambv/black
  rev: stable
  hooks:
    - id: black
      language_version: python3

# - repo: https://github.com/nbQA-dev/nbQA
#   rev: 0.3.5
#   hooks:
#     - id: nbqa-pyupgrade
#       args: [--nbqa-mutate]
#     - id: nbqa-black
#       args: [--nbqa-mutate]
#     - id: nbqa-isort
#       args: [--nbqa-mutate]
#     - id: nbqa-flake8

# - repo: https://github.com/pre-commit/mirrors-isort
#   rev: 'v5.6.4'
#   hooks:
#     - id: isort

# - repo: https://github.com/hadialqattan/pycln
#   rev: v0.0.1 # Possible releases: https://github.com/hadialqattan/pycln/tags
#   hooks:
#     - id: pycln
#       args: [--config=pyproject.toml]